apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::323076901754:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1I8P9026ZM8OZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::323076901754:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-22T17:39:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1991"
  uid: a592f3e4-5870-481c-a01f-1683eaddb888
