apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::323076901754:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1TZOXTUYC48M2
      username: system:node:{{EC2PrivateDNSName}}
      - groups:
        - groups:
        - system:masters
          rolearn: arn:aws:iam::323076901754:role/UdacityFlaskDeployCBKubectlRole
          username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-22T11:54:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1745"
  uid: 03d24000-64bf-48eb-9fdc-c6f49e6d51db
