apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-4-flask-app-deployment
  labels:
    app: project-4-flask-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: flask-app-deployment
    spec:
      containers:
        - name: flask-app-deployment
          image: jbangala/myimage
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
